### ISSUE TITLE
Add Badge on icons to mark new content

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#136]
We consider only Pushed items as relevant new content. How to know these items ? If push is a "flag" of item we could do achieve it by adding an api endpoint /items?flag=push&since=[last_login]. All user's items with flag push from last_login. It could returns any item's types.

I've extracted following code from first theme:
```css
.bg-danger
.navbar .badge-notes{float:right;margin-left:-15px;margin-top:-6px;position: relative;font-size: 11px}
```
