### ISSUE TITLE
carousel crop images

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#250]
# How to reproduce
![infomobi_](https://cloud.githubusercontent.com/assets/9011612/21698091/9a09493a-d37c-11e6-8029-f7fe5b007712.png)

# How to fix

```css
ul[rn-carousel]>li img {
    max-width: 100%;
    max-height: 100%;
    margin: auto;
}
```
